#contenedor base
# version: '3'
# services:
  # mydb:
    # image: postgres
#comando de activación: docker-compose up -d
#comando de detención: docker-compose down

#contenedor con restart y variables de entorno para la db
# version: '3.1'
# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: example

##########################################################
##########################################################
##########################################################
##########################################################
#contenedor con volumenes compartidos con el host
version: "3.1"
services:
  postgres:
    image: postgres:9.5
    # labels:
    # deploy:
    restart: always
    container_name: postgres
    environment:
        - POSTGRES_PASSWORD= "example"
        - POSTGRES_DB= "postgres"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 6551:5432
volumes:
  postgres-data:
##########################################################
##########################################################
##########################################################
##########################################################
